// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVmiaQ4DktHxz9HiDpjfR9ji0olpInE80',
    appId: '1:249271941631:android:5658de27b5fa8fa6880fca',
    messagingSenderId: '249271941631',
    projectId: 'money-manage-5c5bf',
    storageBucket: 'money-manage-5c5bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzXCxomPOsyBvm7wxyeiil3x5SOMI2Fog',
    appId: '1:249271941631:ios:15237c8c4a8ac307880fca',
    messagingSenderId: '249271941631',
    projectId: 'money-manage-5c5bf',
    storageBucket: 'money-manage-5c5bf.firebasestorage.app',
    androidClientId: '249271941631-v01afcue3u12enfeepkhmr0rrdd3cqvv.apps.googleusercontent.com',
    iosClientId: '249271941631-h5pb8tndqr54147m6psldd2b2tu5c7tm.apps.googleusercontent.com',
    iosBundleId: 'vn.nht.manage.money',
  );

}